name: Build Docker Images
on:
  push:
    branches: [master]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        version: ["7.4", "8.0", "8.1", "8.2"]
        variant: ["mysql", "mysql-nginx", "pgsql", "pgsql-nginx"]
    name: ${{ matrix.version }} ${{ matrix.variant }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: docker/${{ matrix.version }}-${{ matrix.variant }}.Dockerfile
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-${{ matrix.variant }}
          cache-from: type=gha,scope=$GITHUB_REF_NAME-${{ matrix.version }}-${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=$GITHUB_REF_NAME-${{ matrix.version }}-${{ matrix.variant }}